baseURL = "https://www.fantasycourt.nl"
languageCode = "nl-nl"
DefaultContentLanguage = "nl"
title = "Fantasy Court Website"
theme = "kotkt"

[languages]
[languages.nl]
name = "Nederlands"
title = "Fantasy Court"
weight = 1

[[languages.nl.menu.main]]
identifier = "visitors"
title = "Bezoekers"
url = "/"
weight = 2

[[languages.nl.menu.main]]
identifier = "vendors"
title = "Standhouders"
url = "/standhouders"
weight = 3

# [[languages.nl.menu.main]]
# identifier = "tourney"
# title = "Toernooiregels"
# url = "/toernooiregels"
# weight = 4


[languages.en]
name = "English"
title = "Fantasy Court"
weight = 1

[[languages.en.menu.main]]
identifier = "visitors"
title = "Visitors"
url = "/"
weight = 2

[[languages.en.menu.main]]
identifier = "vendors"
title = "Vendors and Acts"
url = "/standhouders"
weight = 3

# [[languages.en.menu.main]]
# identifier = "tourney"
# title = "Tourney Rules"
# url = "/toernooiregels"
# weight = 4
